// Code generated by goctl. DO NOT EDIT.
package handler

import (
	"net/http"

	"bigdata/core/internal/svc"

	"github.com/zeromicro/go-zero/rest"
)

func RegisterHandlers(server *rest.Server, serverCtx *svc.ServiceContext) {
	server.AddRoutes(
		[]rest.Route{
			{
				Method:  http.MethodPost,
				Path:    "/country-price-month",
				Handler: countryPriceMonthHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/country-province-price",
				Handler: countryProvincePriceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/data-source",
				Handler: dataSourceHandler(serverCtx),
			},
			{
				Method:  http.MethodPost,
				Path:    "/province-price-month",
				Handler: provincePriceMonthHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/axis",
				Handler: AxisHandler(serverCtx),
			},
			{
				Method:  http.MethodGet,
				Path:    "/test",
				Handler: testHandler(serverCtx),
			},
		},
	)
}
