// Code generated by goctl. DO NOT EDIT.

package models

import (
	"context"
	"database/sql"
	"fmt"
	"strings"

	"github.com/zeromicro/go-zero/core/stores/builder"
	"github.com/zeromicro/go-zero/core/stores/sqlc"
	"github.com/zeromicro/go-zero/core/stores/sqlx"
	"github.com/zeromicro/go-zero/core/stringx"
)

var (
	countryPriceMonthFieldNames          = builder.RawFieldNames(&CountryPriceMonth{})
	countryPriceMonthRows                = strings.Join(countryPriceMonthFieldNames, ",")
	countryPriceMonthRowsExpectAutoSet   = strings.Join(stringx.Remove(countryPriceMonthFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), ",")
	countryPriceMonthRowsWithPlaceHolder = strings.Join(stringx.Remove(countryPriceMonthFieldNames, "`id`", "`create_at`", "`create_time`", "`created_at`", "`update_at`", "`update_time`", "`updated_at`"), "=?,") + "=?"
)

type (
	countryPriceMonthModel interface {
		Insert(ctx context.Context, data *CountryPriceMonth) (sql.Result, error)
		FindOne(ctx context.Context, id int64) (*CountryPriceMonth, error)
		Update(ctx context.Context, data *CountryPriceMonth) error
		Delete(ctx context.Context, id int64) error
	}

	defaultCountryPriceMonthModel struct {
		conn  sqlx.SqlConn
		table string
	}

	CountryPriceMonth struct {
		Id              int64           `db:"id"`
		Day             sql.NullString  `db:"day"`
		PredictionPrice sql.NullFloat64 `db:"prediction_price"`
		AvgPrice        sql.NullFloat64 `db:"avg_price"`
	}
)

func newCountryPriceMonthModel(conn sqlx.SqlConn) *defaultCountryPriceMonthModel {
	return &defaultCountryPriceMonthModel{
		conn:  conn,
		table: "`country_price_month`",
	}
}

func (m *defaultCountryPriceMonthModel) Delete(ctx context.Context, id int64) error {
	query := fmt.Sprintf("delete from %s where `id` = ?", m.table)
	_, err := m.conn.ExecCtx(ctx, query, id)
	return err
}

func (m *defaultCountryPriceMonthModel) FindOne(ctx context.Context, id int64) (*CountryPriceMonth, error) {
	query := fmt.Sprintf("select %s from %s where `id` = ? limit 1", countryPriceMonthRows, m.table)
	var resp CountryPriceMonth
	err := m.conn.QueryRowCtx(ctx, &resp, query, id)
	switch err {
	case nil:
		return &resp, nil
	case sqlc.ErrNotFound:
		return nil, ErrNotFound
	default:
		return nil, err
	}
}

func (m *defaultCountryPriceMonthModel) Insert(ctx context.Context, data *CountryPriceMonth) (sql.Result, error) {
	query := fmt.Sprintf("insert into %s (%s) values (?, ?, ?)", m.table, countryPriceMonthRowsExpectAutoSet)
	ret, err := m.conn.ExecCtx(ctx, query, data.Day, data.PredictionPrice, data.AvgPrice)
	return ret, err
}

func (m *defaultCountryPriceMonthModel) Update(ctx context.Context, data *CountryPriceMonth) error {
	query := fmt.Sprintf("update %s set %s where `id` = ?", m.table, countryPriceMonthRowsWithPlaceHolder)
	_, err := m.conn.ExecCtx(ctx, query, data.Day, data.PredictionPrice, data.AvgPrice, data.Id)
	return err
}

func (m *defaultCountryPriceMonthModel) tableName() string {
	return m.table
}
