// Code generated by goctl. DO NOT EDIT.
package types

type CountryPriceMonthQueryReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type CountryPriceMonthQueryResp struct {
	Data []CountryPriceMonth `json:"data"`
}

type CountryPriceMonth struct {
	Id               int     `json:"id"`
	Day              string  `json:"day"`
	Prediction_price float64 `json:"predictionPrice"`
	Avg_price        float64 `json:"avgPrice"`
}

type CountryProvincePriceQueryReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type CountryProvincePriceQueryResp struct {
	Data []CountryProvincePrice `json:"data"`
}

type CountryProvincePrice struct {
	Id        int     `json:"id"`
	Province  string  `json:"province"`
	Avg_price float64 `json:"avgPrice"`
}

type DataSourceQueryReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type DataSourceQueryResp struct {
	Data []*DataSource `json:"data"`
}

type DataSource struct {
	Id           int     `json:"id"`
	Day          string  `json:"day"`
	Province     string  `json:"province"`
	Address      string  `json:"address"`
	Product_name string  `json:"productName"`
	Category     string  `json:"category"`
	Price        float64 `json:"price"`
}

type ProvincePriceMonthQueryReq struct {
	Page     int `json:"page"`
	PageSize int `json:"pageSize"`
}

type ProvincePriceMonthQueryResp struct {
	Data []ProvincePriceMonth `json:"data"`
}

type ProvincePriceMonth struct {
	Id               int     `json:"id"`
	Province         string  `json:"province"`
	Day              string  `json:"day"`
	Prediction_price float64 `json:"predictionPrice"`
	Avg_price        float64 `json:"avgPrice"`
}
